function scr_create_orig_map(){
ds_list_add(game_map,"Blue Lake Woods 1");
ds_list_add(game_map,"Blue Lake Woods 2");
ds_list_add(game_map,"Highwater Pass 1");
ds_list_add(game_map,"Highwater Pass 2");
ds_list_add(game_map,"Under Skull Mountain 1");
ds_list_add(game_map,"Under Skull Mountain 2");
ds_list_add(game_map,"Under Skull Mountain 3");
ds_list_add(game_map,"Isle of the Lion Lord");
ds_list_add(game_map,"Hills of the Warrior 1");
ds_list_add(game_map,"Hills of the Warrior 2");
ds_list_add(game_map,"Windy City");
ds_list_add(game_map,"Sinister Sewers");
ds_list_add(game_map,"The Crystal Crags 1");
ds_list_add(game_map,"The Crystal Crags 2");
ds_list_add(game_map,"Dragonspike");
ds_list_add(game_map,"Stormwalk Mountain");
ds_list_add(game_map,"Shishkaboss");
ds_list_add(game_map,"The Whispering Woods 1");
ds_list_add(game_map,"The Whispering Woods 2");
ds_list_add(game_map,"Devil's Marsh 1");
ds_list_add(game_map,"Devil's Marsh 2");
ds_list_add(game_map,"Knight's Isle");
ds_list_add(game_map,"Whale Grotto");
ds_list_add(game_map,"Hoverboard Beach");
ds_list_add(game_map,"Pyramids of Peril");
ds_list_add(game_map,"Madmaze Mountain");
ds_list_add(game_map,"The Deadly Skyscrapers");
ds_list_add(game_map,"Skydragon Castle 1");
ds_list_add(game_map,"Skydragon Castle 2");
ds_list_add(game_map,"Coral Blade Grotto");
ds_list_add(game_map,"Boomerang Bosses");
ds_list_add(game_map,"Woods of Despair 1");
ds_list_add(game_map,"Woods of Despair 2");
ds_list_add(game_map,"Forced Entry");
ds_list_add(game_map,"The Cliffs of Illusion");
ds_list_add(game_map,"Lion's Den");
ds_list_add(game_map,"Wind Castles 1");
ds_list_add(game_map,"Wind Castles 2");
ds_list_add(game_map,"Blizzard Mountain");
ds_list_add(game_map,"Caves of Ice");
ds_list_add(game_map,"The Nightmare Peaks 1");
ds_list_add(game_map,"The Nightmare Peaks 2");
ds_list_add(game_map,"Bagel Brothers");
ds_list_add(game_map,"Diamond Edge");
ds_list_add(game_map,"The Hills Have Eyes");
ds_list_add(game_map,"Secrets in the Rocks");
ds_list_add(game_map,"Ice God's Vengeance");
ds_list_add(game_map,"Beneath the Twisted Hills");
ds_list_add(game_map,"Alien Isle");
ds_list_add(game_map,"The Land Below");
ds_list_add(game_map,"The Final Marathon");
ds_list_add(game_map,"Plethora");
ds_list_add(game_map,"The Pinnacle");
ds_list_add(game_map,"Hidden Canyon");
ds_list_add(game_map,"The Caged Beasts");
ds_list_add(game_map,"Crab Cove");
ds_list_add(game_map,"The Forbidden Tombs");
ds_list_add(game_map,"Stairway to Oblivion");
ds_list_add(game_map,"The Valley of Life");
ds_list_add(game_map,"The Black Pit");
ds_list_add(game_map,"Frosty Doom");
ds_list_add(game_map,"Bloody Swamp");
ds_list_add(game_map,"Scorpion Isle");
ds_list_add(game_map,"Towers of Blood");
ds_list_add(game_map,"The Crypt");
ds_list_add(game_map,"Alien Twilight");
ds_list_add(game_map,"Tunnels Beneath the Woods");
ds_list_add(game_map,"Hills of Forever");
ds_list_add(game_map,"Monster Island");
ds_list_add(game_map,"The Shimmering Caves");
ds_list_add(game_map,"Sky Fortress");
ds_list_add(game_map,"Elsewhere 1");
ds_list_add(game_map,"Elsewhere 2");
ds_list_add(game_map,"Elsewhere 3");
ds_list_add(game_map,"Elsewhere 4");
ds_list_add(game_map,"Elsewhere 5");
ds_list_add(game_map,"Elsewhere 6");
ds_list_add(game_map,"Elsewhere 7");
ds_list_add(game_map,"Elsewhere 8");
ds_list_add(game_map,"Elsewhere 9");
ds_list_add(game_map,"Elsewhere 10");
ds_list_add(game_map,"Elsewhere 11");
ds_list_add(game_map,"Elsewhere 12");
ds_list_add(game_map,"Elsewhere 13");
ds_list_add(game_map,"Elsewhere 14");
ds_list_add(game_map,"Elsewhere 15");
ds_list_add(game_map,"Elsewhere 16");
ds_list_add(game_map,"Elsewhere 17");
ds_list_add(game_map,"Elsewhere 18");
ds_list_add(game_map,"Elsewhere 19");
ds_list_add(game_map,"Elsewhere 20");
ds_list_add(game_map,"Elsewhere 21");
ds_list_add(game_map,"Elsewhere 22");
ds_list_add(game_map,"Elsewhere 23");
ds_list_add(game_map,"Elsewhere 24");
ds_list_add(game_map,"Elsewhere 25");
ds_list_add(game_map,"Elsewhere 26");
ds_list_add(game_map,"Elsewhere 27");
ds_list_add(game_map,"Elsewhere 28");
ds_list_add(game_map,"Elsewhere 29");
ds_list_add(game_map,"Elsewhere 30");
ds_list_add(game_map,"Elsewhere 31");
ds_list_add(game_map,"Elsewhere 32");
}